# Generated by Django 3.0.7 on 2020-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommand',
            name='adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='recommand',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recommand',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recommand',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
    ]
